baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = 'blogtheme'

[markup.goldmark.renderer]
unsafe= true

[menu]
    
    [[menu.main]]
        name = 'About'
        url = '/about'
        weight = 20
    [[menu.main]]
        name = 'Blog'
        url = '/posts'
        weight = 30
